# An example of ClusterConfig object using an existing VPC:
# You can find more examples in https://github.com/eksctl-io/eksctl/tree/main/examples
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: ap-south-1
  version: "1.29"

vpc:
  id: "vpc-0dd338ecf29863c55"
  subnets:
    public:
      ap-south-1b:
          id: "subnet-0eac95c017d896556"
      ap-south-1c:
          id: "subnet-053d2e8122b54debf"

iam:
  withOIDC: true

managedNodeGroups:
- name: cloud-eks-workers
  desiredCapacity: 1
  iam:
    withAddonPolicies:
      albIngress: true
  instanceTypes: ["t2.small","t3.large"]
  spot: true

cloudWatch:
    clusterLogging:
        enableTypes: ["audit", "authenticator", "controllerManager"]
